language: node_js
node_js:
  - "v11.14.0"
branches:
  only:
    - blog    # build master branch only
cache:
  directories:
    - node_modules # cache dir

before_install:
  - export TZ='Asia/Shanghai'  # set timezone
  - npm install -g hexo

#install:
#  - npm install -g gitbook-cli # install compile tool
#  - gitbook install

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  # keep-history: true
  local-dir: ./public/  # static output dir
  target-branch: gh-pages
  verbose: true
  on:
    branch: blog
  
